name: Clojure CI

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test

    - uses: actions/checkout@v1
    - uses: DeLaGuardo/clojure-lint-action@v1
      with:
        clj-kondo-args: --lint .
        github_token: ${{ secrets.GITHUB_TOKEN }}